site_name: LoRa App Server - open-source LoRaWAN application-server
repo_url: https://github.com/brocaar/lora-app-server
theme_dir: docs/material
include_next_prev: False

pages:
  - index.md
  - features.md
  - getting-started.md
  - mqtt-topics.md
  - activating-nodes.md
  - api.md
  - configuration.md
  - frequently-asked-questions.md
  - changelog.md

extra:
  version: '0.6.0'
  github:
    download_release: true

markdown_extensions:
  - admonition
  - codehilite(css_class=code)

google_analytics: ['UA-3512995-9', 'docs.loraserver.io']

extra_javascript:
  - js/gitter.js
  - https://sidecar.gitter.im/dist/sidecar.v1.js
